import type { Direction, LevelDefinition, TileDefinition } from "../../types/game";

const E = (): TileDefinition => ({ kind: "empty" });
const W = (): TileDefinition => ({ kind: "wall" });
const G = (): TileDefinition => ({ kind: "goal" });
const T = (): TileDefinition => ({ kind: "trap" });
const GU = (): TileDefinition => ({ kind: "gateUp" });
const GD = (): TileDefinition => ({ kind: "gateDown" });
const O = (direction: Direction): TileDefinition => ({ kind: "oneWay", direction });
const S = (id: string): TileDefinition => ({ kind: "switch", id });
const D = (id: string): TileDefinition => ({ kind: "door", id });
const P = (id: string): TileDefinition => ({ kind: "teleport", id });

export const levels: LevelDefinition[] = [
  {
    id: 1,
    name: "First Inversion",
    start: { x: 0, y: 4 },
    rulePoints: 1,
    moveLimit: 8,
    grid: [
      [W(), W(), G(), W(), W()],
      [W(), W(), GU(), W(), W()],
      [W(), W(), GU(), W(), W()],
      [W(), E(), GU(), E(), E()],
      [E(), E(), E(), W(), E()],
    ],
  },
  {
    id: 2,
    name: "Keyed Lift",
    start: { x: 0, y: 4 },
    rulePoints: 1,
    moveLimit: 10,
    grid: [
      [W(), G(), W(), W(), W()],
      [W(), D("a"), GU(), W(), W()],
      [W(), W(), GU(), W(), W()],
      [W(), S("a"), GU(), E(), E()],
      [E(), E(), E(), W(), E()],
    ],
  },
  {
    id: 3,
    name: "False Shortcut",
    start: { x: 0, y: 4 },
    rulePoints: 1,
    moveLimit: 11,
    grid: [
      [W(), G(), W(), W(), W()],
      [W(), D("a"), GU(), T(), W()],
      [W(), W(), GU(), W(), W()],
      [W(), S("a"), GU(), E(), E()],
      [E(), O("up"), E(), W(), E()],
    ],
  },
  {
    id: 4,
    name: "Split Decision",
    start: { x: 0, y: 5 },
    rulePoints: 1,
    moveLimit: 12,
    grid: [
      [W(), W(), G(), W(), W(), W()],
      [W(), D("a"), GU(), T(), E(), W()],
      [W(), E(), GU(), W(), E(), W()],
      [W(), S("a"), W(), W(), E(), W()],
      [W(), E(), E(), E(), E(), W()],
      [E(), E(), W(), T(), E(), E()],
    ],
  },
  {
    id: 5,
    name: "Relay Port",
    start: { x: 0, y: 5 },
    rulePoints: 1,
    moveLimit: 13,
    grid: [
      [W(), W(), G(), W(), W(), W()],
      [W(), D("a"), GU(), W(), P("x"), W()],
      [W(), E(), GU(), W(), E(), W()],
      [W(), S("a"), W(), W(), E(), W()],
      [W(), E(), E(), E(), E(), W()],
      [E(), E(), W(), P("x"), T(), E()],
    ],
  },
  {
    id: 6,
    name: "Trap Ledger",
    start: { x: 0, y: 5 },
    rulePoints: 1,
    moveLimit: 12,
    grid: [
      [W(), W(), G(), W(), W(), W()],
      [W(), D("a"), GU(), T(), E(), W()],
      [W(), E(), GU(), W(), E(), W()],
      [W(), S("a"), O("right"), E(), E(), W()],
      [W(), O("up"), E(), E(), E(), W()],
      [E(), E(), W(), P("x"), T(), E()],
    ],
  },
  {
    id: 7,
    name: "Locked Return",
    start: { x: 0, y: 5 },
    rulePoints: 2,
    moveLimit: 14,
    grid: [
      [W(), W(), G(), W(), W(), W()],
      [W(), D("a"), GU(), W(), D("b"), W()],
      [W(), E(), GU(), E(), E(), W()],
      [W(), S("a"), W(), W(), S("b"), W()],
      [W(), E(), E(), E(), E(), W()],
      [E(), E(), W(), T(), E(), E()],
    ],
  },
  {
    id: 8,
    name: "Gate Count",
    start: { x: 0, y: 5 },
    rulePoints: 2,
    moveLimit: 14,
    grid: [
      [W(), W(), G(), W(), W(), W()],
      [W(), GU(), D("a"), W(), W(), W()],
      [W(), GU(), E(), E(), E(), W()],
      [W(), S("a"), W(), W(), GU(), W()],
      [W(), E(), E(), E(), GU(), W()],
      [E(), E(), W(), T(), E(), E()],
    ],
  },
  {
    id: 9,
    name: "Bridge Order",
    start: { x: 0, y: 5 },
    rulePoints: 2,
    moveLimit: 16,
    grid: [
      [W(), W(), G(), W(), W(), W()],
      [W(), D("a"), GU(), W(), D("b"), W()],
      [W(), E(), GU(), E(), E(), W()],
      [W(), S("b"), W(), W(), S("a"), W()],
      [W(), E(), P("x"), E(), E(), W()],
      [E(), E(), W(), P("x"), T(), E()],
    ],
  },
  {
    id: 10,
    name: "Exit Tax",
    start: { x: 0, y: 5 },
    rulePoints: 2,
    moveLimit: 16,
    grid: [
      [W(), W(), G(), W(), W(), W()],
      [W(), D("a"), GU(), T(), D("b"), W()],
      [W(), E(), GU(), E(), E(), W()],
      [W(), S("b"), W(), W(), S("a"), W()],
      [W(), E(), P("x"), T(), E(), W()],
      [E(), E(), W(), P("x"), E(), E()],
    ],
  },
  {
    id: 11,
    name: "Double Bind",
    start: { x: 0, y: 5 },
    rulePoints: 2,
    moveLimit: 17,
    grid: [
      [W(), W(), G(), W(), W(), W()],
      [W(), D("a"), GU(), W(), D("b"), W()],
      [W(), E(), GU(), E(), E(), W()],
      [W(), S("a"), W(), W(), S("b"), W()],
      [W(), E(), P("x"), T(), E(), W()],
      [E(), E(), W(), P("x"), E(), E()],
    ],
  },
  {
    id: 12,
    name: "Delayed Consequence",
    start: { x: 0, y: 5 },
    rulePoints: 2,
    moveLimit: 17,
    grid: [
      [W(), W(), G(), W(), W(), W()],
      [W(), D("a"), GU(), W(), D("b"), W()],
      [W(), E(), GU(), E(), GD(), W()],
      [W(), S("b"), W(), W(), S("a"), W()],
      [W(), E(), P("x"), E(), E(), W()],
      [E(), E(), W(), P("x"), T(), E()],
    ],
  },
  {
    id: 13,
    name: "Loop Theory",
    start: { x: 0, y: 5 },
    rulePoints: 2,
    moveLimit: 18,
    grid: [
      [W(), W(), G(), W(), W(), W()],
      [W(), D("a"), GU(), W(), D("b"), W()],
      [W(), E(), GU(), E(), GD(), W()],
      [W(), S("b"), W(), O("right"), S("a"), W()],
      [W(), E(), P("x"), E(), E(), W()],
      [E(), E(), W(), P("x"), T(), E()],
    ],
  },
  {
    id: 14,
    name: "Misdirect Chamber",
    start: { x: 0, y: 5 },
    rulePoints: 2,
    moveLimit: 18,
    grid: [
      [W(), W(), G(), W(), W(), W()],
      [W(), D("a"), GU(), T(), D("b"), W()],
      [W(), E(), GU(), E(), GD(), W()],
      [W(), S("b"), W(), O("right"), S("a"), W()],
      [W(), E(), P("x"), E(), E(), W()],
      [E(), E(), W(), P("x"), T(), E()],
    ],
  },
  {
    id: 15,
    name: "Adult Proof",
    start: { x: 0, y: 5 },
    rulePoints: 2,
    moveLimit: 19,
    grid: [
      [W(), W(), G(), W(), W(), W()],
      [W(), D("a"), GU(), T(), D("b"), W()],
      [W(), E(), GU(), E(), GD(), W()],
      [W(), S("b"), W(), O("right"), S("a"), W()],
      [W(), E(), P("x"), E(), E(), W()],
      [E(), E(), W(), P("x"), T(), E()],
    ],
  },
];
